# Generated by Django 5.2.15 on 2026-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='family_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
